### PR TITLE
Added functionality to copy decrypted addon directly into game folder.

### PR DESCRIPTION
**Pull request by Chiplis**

### CODE REVIEW

**Review by MarkMeltzer — APPROVED** [review]
Good addition!

Small question, though. Why does "_decrypt_addon_start()" need to be wrapped in "decrypt_addon_start(HLA_root_path)"?

**Comment by Chiplis** [comment]
Since "decrypt_addon_start" now takes a parameter for HLA's installation folder, but threading.Thread's "target" is supposed to be a function reference. Wrapping the function allows you to execute it in a new thread while still holding some variable internal state.

**Comment by MarkMeltzer** [comment]
But couldn't you just add the arguments with "args="?

Also not sure why the HLA root path needs to be passed anyway, since both decrypt_addon_start() and decrypt_addon_finish() are defined in the scope of decrypt() they have access to its variables. Just like addon_zip_path for example.

**Comment by Chiplis** [comment]
Had forgotten about the 'args=' parameter! Just pushed some changes which remove the unnecessary HLA_root_path argument, and also deal with automatically closing/opening the required files using Python's 'with' context handler.

There's a weird bug right now which throws an "File is not a zip file" exception if you try decrypting twice. Still not entirely sure what's going on there, but restarting the application seems to fix it.

**Comment by MarkMeltzer** [comment]
Ah cool.

I think I know where the bug comes from. We overwrite the original .zip after decrypting it (on line 94). Which means when running the decryption a second time we are essentially encryption it again, so when trying to read that mangled data on line 97 it throws an error. I'll fix it by using a temp file and leaving the original zip as is.

**Comment by Chiplis** [comment]
Ahh, of course! I had thought of that as well, but was still confused as to why the decryption would fail when running a 2nd time and succeed on the third attempt. But it makes sense when considering that the decryption is done via XORing the contents, running every 2n time would simply re-encrypt the file, while every 2n+1 time will decrypt it.

**Pull request merged**
